# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 10:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=20000, verbose_name='\u5185\u5bb9'),
        ),
    ]
